// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/three/three-css3drenderer.d.ts
declare namespace THREE {
    class CSS3DObject extends Object3D {
        constructor(element: any);

        element: any;
    }

    class CSS3DSprite extends CSS3DObject {
        constructor(element: any);

    }


    class CSS3DRenderer {
        constructor();

        domElement:HTMLElement;

        setSize(width: number, height: number): void;
        render(scene: THREE.Scene, camera: THREE.Camera): void;
    }
}
