// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/three/three-shaderpass.d.ts
declare namespace THREE {
	export class ShaderPass {
		constructor( shader: Shader, textureID?: string );

		textureID: string;
		uniforms: any;
		material: ShaderMaterial;
		renderToScreen: boolean;
		enabled: boolean;
		needsSwap: boolean;
		clear: boolean;
		camera: Camera;
		scene: Scene;
		quad: Mesh;

		render(renderer: WebGLRenderer, writeBuffer: WebGLRenderTarget, readBuffer: WebGLRenderTarget, delta: number): void;
	}
}
