// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/three/three-copyshader.d.ts
declare namespace THREE {
	export var CopyShader: Shader;
}
