// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/three/three-editorcontrols.d.ts
declare namespace THREE {

  class EditorControls extends EventDispatcher {

    constructor(object: Camera, domElement?:HTMLElement);

    enabled: boolean;
    center: THREE.Vector3;

    focus(target: THREE.Object3D, frame: boolean): void;
    pan(delta: THREE.Vector3): void;
    zoom(delta: THREE.Vector3): void;
    rotate(delta: THREE.Vector3): void;
    dispose(): void;

  }

}
