// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/three/detector.d.ts
interface DetectorStatic {
	canvas: boolean;
	webgl: boolean;
	workers: boolean;
	fileapi: boolean;

	getWebGLErrorMessage(): HTMLElement;
	addGetWebGLMessage(parameters?: {id?: string; parent?: HTMLElement}): void;
}

declare var Detector: DetectorStatic;
